# Generated by Django 5.2.4 on 2025-07-10 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='core.course'),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='group_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupstudent'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.groupstudent'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='students_group', to='core.groupstudent'),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='core.course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(related_name='teachers', to='core.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='teacher',
            field=models.ManyToManyField(related_name='groups_taught', to='core.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'group', 'date')},
        ),
    ]
